msgpack/msgpack-python

msgpack/_packer.pyx
msgpack/pack.h

Fix build failuer for Python 2.7 on Windows.

---

.travis.yml
tox.ini

Building Cython for every test makes test slow.
Travis-CI's new Docker based environment supports cache.  So prepare whl for Cython.

Use wheelhouse for cython

---

test/test_unpack.py

Adjust the skipif conditional to use the older pytest 2.3 syntax.
(This allows the tests to pass with the system pytest package on RHEL 7.0, since RHEL 7.0 ships pytest 2.3.5. See downstream bug https://bugzilla.redhat.com/1182808)

tests: add pytest 2.3 compatibility

---

.travis.yml
msgpack/_unpacker.pyx
msgpack/fallback.py
msgpack/unpack.h
test/test_limits.py
tox.ini

And fix build error on 32bit environment (fixes #102).

Add max_<type>_len option to unpacker. (fixes #97).

---

.travis.yml
msgpack/_unpacker.pyx
msgpack/unpack.h
msgpack/unpack_template.h

fix compiler warnings

---

.travis.yml

See documentation here http://docs.travis-ci.com/user/caching/#pip-cache

Travis will now cache dependencies despite having a custom install step

---

msgpack/_packer.pyx

Fix wrong 'dict is too large' on unicode string

---

ChangeLog.rst
msgpack/_packer.pyx
msgpack/fallback.py
test/test_stricttype.py

Current packer accepts child types and doesn't distinguish list and tuples.
It means you can't hook encoding named tuple with `default` function.
This PR adds `strict_types` option.  When it is enabled, Packer doesn't accept
child types and tuples.
fixes #142
fixes #98
(This PR is follow up of #100 since there were no response from original author.)

Packer: check type strictly

---

msgpack/_packer.pyx
msgpack/fallback.py

This will make precise python types serialization possible.

added distinguish_tuple argument to Packer

---

msgpack/_packer.pyx
msgpack/fallback.py
test/test_memoryview.py

I am working on a high-throughput scenario where I need to avoid copying memory wherever possible. I frequently create buffers from existing objects and sometimes need to hand them to msgpack.
Unfortunately I could not find a way to pass buffers to the current version of msgpack without copying.
So I wrote this small patch to support packing arbitrary buffer objects to binary data. It works well for my use case.
Things I'm not so sure about:
* Pure Python fallback is not implemented. Its structure is different from the Cython code and I'm not sure what to do exactly.
* I'm not an expert in using this library. Does this interfere with any other functionality?
* Information is lost in the conversion, e.g., shape of Numpy arrays. Since the lib just "swallows" everything that is a buffer. A …

Support packing memoryview objects

---

msgpack/_packer.pyx
msgpack/_unpacker.pyx
msgpack/exceptions.py
msgpack/fallback.py
test/test_limits.py

I noticed that when I use the message fallback instead of the cython i get different Exception. On my way to fixing this I tried to improve the exceptions in general.
The branch does the following improvements:
1. All exceptions inherit from MsgpackBaseException.
2. The fallback and the cython throw the same exception type.
3. Added new exception PackOverflowError for backwards  compatibility.

Excepetions hierarchy

---

msgpack/_packer.pyx
msgpack/_unpacker.pyx
msgpack/exceptions.py
msgpack/fallback.py
test/test_limits.py

Organize Exceptions

---

msgpack/_packer.pyx
msgpack/fallback.py
test/test_memoryview.py

Hi,
This PR addresses issues pointed out in https://github.com/msgpack/msgpack-python/issues/126#issuecomment-214425711
- The pure python fallback used the length, not the number of bytes of a memoryview. Views with multi-byte types would be prefixed with a fraction of their real length.
- Packing without ``use_bin_type=True`` and unpacking with encoding set leads to errors. ``use_bin_type=True`` is now enforced for memoryviews to avoid this.
- Add some tests that pack/unpack memoryviews of different types and sizes.

Fix problems associated with packing memoryviews

---

msgpack/fallback.py

bytearray may be best option for buffer.
But PyPy's struct.unpack is slower on bytearray.
So we use bytes for now.

fallback: Rewrite buffer from array of bytes to bytes

---

msgpack/_unpacker.pyx
msgpack/fallback.py
test/test_buffer.py

This PR adds support for unpacking/feeding from any object that supports the new buffer interface.
For compatibility, an attempt is made to use the old buffer interface if that fails. On success, a ``RuntimeWarning`` is issued to inform users of possible errors and future removal of this feature.

Use new buffer interface to unpack

---

ChangeLog.rst
README.rst
appveyor.yml
docs/api.rst
docs/index.rst
msgpack/_packer.pyx
msgpack/_unpacker.pyx
msgpack/fallback.py
test/test_extension.py
test/test_pack.py

cosmetic issues:
- reST headlines' underline length needs to match the headline length
(looks like somebody is / was using a proportional font)
- Cython code lines do not need to be terminated with a semicolon
- always use triple-double-quotes for docstrings
I did the PR against release-0.4 branch, hope this is correct to get it fixed in next release and also get it merged from there into master.

fix typos and other cosmetic issues

---

.travis.yml
appveyor.yml
docker/runtests.sh

travis:
* stop using tox
* Add Python 3.6 and 3.7-dev
* Stop pypy3 (until PyPy3.5 is released)
appveyor:
* Add Python 3.6.

travis update

---

msgpack/_unpacker.pyx
msgpack/fallback.py
test/test_sequnpack.py

There seems to be a demand for tracking offset (e.g., for indexing) while unpacking from stream. Before 1.0, it is suggested to use `write_bytes` for that purpose. Since it was really easy and a lot more efficient, this PR adds a `tell()` method to `Unpacker`.

Unpacker: add tell()

---

msgpack/fallback.py
test/test_stricttype.py

Also, fix formatting of error message in case of tuple.
See https://github.com/msgpack/msgpack-python/issues/245

Add unittests to document serialisation of tuples

---

.gitignore
.travis.yml
test/test_pack.py

Same as https://github.com/msgpack/msgpack-python/pull/249 but without 3.3 and 3.4 removal

Remove code and tests for unsupported Python 2.6

---

msgpack/_packer.pyx

0.5.2 introduced a regression in `Packer`.  Specifying only `unicode_errors` without `encoding` results in `self.unicode_errors` *not* being set to the result of `PyBytes_AsString`.
Previously, `unicode_errors` was either set to `NULL` or to the result of `PyBytes_AsString`. This restores that behavior while also keeping the new `NULL` default behavior when both are unspecified.
Original defaults of `utf-8` and `strict` were restored to keep API compatibility until these deprecated options are finally removed.
See https://github.com/neovim/python-client/issues/299 for downstream issues.

Fix unicode_errors encoding

---

msgpack/_packer.pyx
msgpack/_unpacker.pyx

Temporal bytes object is not needed in Python 3.3+.

Use cython's cast for converting encoding and errors

---

msgpack/fallback.py

fallback: Fix error on Jython

---

msgpack/_unpacker.pyx
msgpack/fallback.py

To avoid DoS attack, make default size limit smaller.
Fixes #295

unpacker: Make default size limit smaller

---

msgpack/pack_template.h
msgpack/unpack_template.h

use _PyFloat APIs to (de)serialize float and double

---

msgpack/__init__.py
msgpack/_packer.pyx
msgpack/_unpacker.pyx
msgpack/fallback.py

This should not change anything but makes it easier to bundle msgpack in other projects (where bundling involves copying msgpack's source code and exposing it under a different Python module name).
Some applications use msgpack to store persistent data and require a specific msgpack version (e.g. borgbackup). Bundling helps in case there is an (incompatible) version of msgpack in a system-wide install.
More background for this change in #356

use relative imports

---

README.rst
msgpack/_packer.pyx
msgpack/_unpacker.pyx
msgpack/fallback.py
test/test_buffer.py
test/test_case.py
test/test_format.py
test/test_memoryview.py
test/test_newspec.py
test/test_read_size.py
test/test_sequnpack.py

Use new msgpack spec by default.

---

msgpack/fallback.py
test/test_sequnpack.py

Fix fallback Unpacker.read()

---

msgpack/_packer.pyx

There are only 2 values possible: True or False. Checking for the type first and then the value is an unnecessary overhead.

Simplify check for bool type

---

msgpack/ext.py

When overriding `__eq__`, `__hash__` should be overridden too.

Make Timestamp hashable

---

tox.ini

The py27-c variant is failing under Tox, with
```
py27-c run-test-pre: PYTHONHASHSEED='1597877995'
py27-c runtests: commands[0] | python -c 'from msgpack import _cmsgpack'
Traceback (most recent call last):
File "<string>", line 1, in <module>
ImportError: cannot import name _cmsgpack
ERROR: InvocationError for command
'/home/alex/src/msgpack-python/.tox/py27-c/bin/python -c from msgpack
import _cmsgpack' (exited with code 1)
```
As the Changelog notes, release 1.0 will drop support for the native
extension on CPython 2.x. So there seems little benefit of testing it.

build: Don't test C extension on CPython 2.7 under Tox

---

README.md

The example to unpack a datetime does not work on python3 at least because the condition is based on a binary string instead of an unicode one, so I changed it

Fix an example in README.md

---

msgpack/_unpacker.pyx
msgpack/fallback.py
test/test_unpack.py

Fixes the inconsistency in `Unpacker.tell()` between cmsgpack and fallback reported in #426. Also fixes inconsistency with read size greater remaining bytes in input, add tests for tell and doc tell.

fix #426, add doc to Unpacker.tell(), add tests for tell

---

ChangeLog.rst

`max_buffer_type` -> `max_buffer_size`

Fix a typo in the changelog

---

msgpack/ext.py

`datetime.datetime.fromtimestamp(-1)` does not work (at least not on Win10, Python 3.7).
A mitigation mentioned [here](https://stackoverflow.com/questions/17231711/how-to-create-datetime-from-a-negative-epoch-in-python/17231712) is to use
```python
datetime.datetime.fromtimestamp(0) + datetime.timedelta(seconds=-1)
```
instead.

fix: allow for timestamps before UNIX epoch

---

msgpack/fallback.py

The handling of datetime is different in the cython and Python implementations. In contrast to the docs, timezone is not required in the Python implementation.

Synchronize handling of datetime in Packer implementations

---

Makefile
msgpack/unpack.h
test/test_timestamp.py

Cython implementation still used datetime.from_timestamp method, which does not work on windows.
Update the cython implementation to use utc time and delta
and add a regression test to highlight the issue.

fix: datetime before epoch on windows in cython implementation

---

.github/workflows/linux.yml
Makefile

With the increase of Arm CPUs in datacenters and the upcoming Apple migration to Arm, the use of Python on these platforms is growing. However, installing Python modules without Wheels is often fails or it is very slow. The error messages users see are not clearly identifying the problem as missing build dependency. Publishing a Wheel is typically low effort, just a few lines in the build script. For users this saves significant time by avoiding troubleshooting and not having to wait for build processes to finish.
I was happy to see msgpack already uses travis.com for testing on arm64. To minimize impact on the repository, I suggest building arm64 wheels using the existing github actions, with qemu-user-static. Would be happy to hear any comments you might have.
Thank you!
Tsahi.

Arm64 wheel

---

msgpack/fallback.py

I refactored the code in the `_read_header()` method of the `fallback.py` file.
I removed duplicated code and (hopefully) made the function more readable and maintainable.

Refactor fallback' read header

---

pyproject.toml
requirements.txt
tox.ini

This change causes Tox to run the project's setup.py in a virtualenv
(default path is .tox/.package). The required version of Cython is
installed, rather than whatever version is installed system wide. I
found that this eliminated test suite failures under CPython 3.8, that
were due to me having a version of Cython that was too old to generate a
compatible _cmsgpack.cpp.
isolated_build was released in Tox 3.3.0, released 2018-09-11.
e.g.
```
± tox -r
.package create: /home/alex/src/msgpack-python/.tox/.package
.package installdeps: setuptools >= 35.0.2, Cython~=0.29.13, pytest
py27-pure recreate: /home/alex/src/msgpack-python/.tox/py27-pure
py27-pure installdeps: pytest
py27-pure inst:
/home/alex/src/msgpack-python/.tox/.tmp/package/1/msgpack-1.0.0rc1.tar.gz
...
py27-x86 create: …
```

build: Create tox environments using a known Cython version

---

msgpack/_unpacker.pyx
msgpack/fallback.py

fix docstring

---

test/test_unpack.py

It looks like you are using `pytest`. `pytest` has automatic test discovery. There is no need for test files to have `__main__`. Also: this code was out of date - it executes only 4 out of 5 tests.

Remove redundant code

---

msgpack/fallback.py

While working on adding hypothesis-powered tests https://github.com/hexagonrecursion/msgpack-python/commit/f286bd28061098180c2eec6deeefdfc919f7d6f3 I have noticed several places where you use the wrong formatting syntax when throwing an exception:
```py
>>> ValueError("%s exceeds max_str_len(%s)", 10, 5)
ValueError('%s exceeds max_str_len(%s)', 10, 5)
>>> ValueError("%s exceeds max_str_len(%s)" % (10, 5))
ValueError('10 exceeds max_str_len(5)')
```

Fix error formatting

---

msgpack/_unpacker.pyx

Also "old" buffer API was removed in Python 3.10

Remove unused PyObject_AsReadBuffer definition

---

setup.py

`msgpack-python` has an optional C extension. Sometimes people may want to build a wheel or an egg that can be used on all platforms and has the appropriate metadata (eg `py3-none-any` wheel). Example: https://github.com/ionrock/cachecontrol/issues/160. With this little addition to setup.py I can build `msgpack-1.0.2-py3.9.egg` like this:
```sh
MSGPACK_PUREPYTHON=1 ./setup.py bdist_egg
```

Make pure-python wheels and eggs possible

---

msgpack/_unpacker.pyx

Cython already has its out [internal definition](https://github.com/cython/cython/blob/0.29.x/Cython/Includes/libc/stdint.pxd#L16) of `uint64_t` so it might as well  be used here. In addition `ctypedef` causes a build break if `msgpack` is compiled with Cython3.

cimport uint64_t instead of using ctypedef

---

msgpack/unpack.h

It took me a while to figure out that the strict_map_key flag was involved in the generation of this exception. Even though the readme mentions the behaviour, it would be nice to make the exception message more explicit.

Clearify unpack exception related to key type and strict_map_key flag

---

msgpack/_packer.pyx
msgpack/fallback.py
test/test_timestamp.py

When attempting to pack a `datetime.datetime` object with `msgpack.packb(dt, datetime=True)` where the `dt` object is missing `tzinfo`, the library throws the generic error `TypeError: can not serialize 'datetime.datetime' object`.
That threw me off as I thought the problem related to `datetime=True`, and didn't realise I was missing `tzinfo`. This small patch outputs a more specific error message for that edge case.

Nicer error when packing a datetime without tzinfo

---

msgpack/fallback.py
setup.py

Ref: https://github.com/borgbackup/borg/issues/6105

Don't define __*_ENDIAN__ macro on Unix.

---

msgpack/pack_template.h
msgpack/unpack_template.h

Python 3.11a7 adds public functions:
* PyFloat_Pack4(), PyFloat_Pack8()
* PyFloat_Unpack4(), PyFloat_Unpack8()
https://bugs.python.org/issue46906

Use PyFloat_Pack8() on Python 3.11a7

---

msgpack/_unpacker.pyx
msgpack/fallback.py
test/test_sequnpack.py

Fix Unpacker max_buffer_length handling

---

msgpack/sysdep.h

On some systems (I tested it on Oracle Solaris and FreeBSD),  `__BYTE_ORDER`, `__LITTLE_ENDIAN` and `__BIG_ENDIAN` from `arpa/inet.h` are not available, which can cause failures on big endian systems (because little endian is the default). This adds a fallback to common compiler defines in those cases.
Addresses issues raised in #495.

Fallback to compiler defines when __BYTE_ORDER is not available

---

.github/workflows/wheel.yml
setup.cfg

Now that cpython 3.11.0rc1 is out (ABI stable), we can publish cp311 wheels.
This bumps cibuildwheel to 2.9.0 which now builds cp 3.11 wheels.

Add python 3.11 wheels

---

README.md

The project don't use CircleCI anymore. So this PR switch the badge/link to point out to github workflow instead.

fix: build status badge

---

README.md
docs/conf.py
msgpack/__init__.py
msgpack/_packer.pyx
msgpack/_unpacker.pyx
msgpack/ext.py
msgpack/fallback.py
setup.py
test/test_buffer.py
test/test_case.py
test/test_except.py
test/test_extension.py
test/test_memoryview.py
test/test_pack.py
test/test_timestamp.py
test/test_unpack.py
tox.ini

The PR removes python2 references and cases.
`tox` command is green on cpython3.9 (py39-c and py39-pure) on my local machine.
Close #518

Drop python2 support

---

Makefile
msgpack/__init__.py
msgpack/ext.py
msgpack/fallback.py
pyproject.toml
requirements.txt
setup.cfg
setup.py
test/test_buffer.py
test/test_case.py
test/test_except.py
test/test_extension.py
test/test_format.py
test/test_limits.py
test/test_memoryview.py
test/test_newspec.py
test/test_obj.py
test/test_pack.py
test/test_seq.py
test/test_sequnpack.py
test/test_stricttype.py
test/test_subtype.py
test/test_unpack.py

The following steps have been taken:
1. Black was updated to latest version. The code has been formatted with the new version.
2. The pyupgrade utility is installed. This helped to remove all the code that was needed to support Python < 3.7.
Related issue – #541.

Drop Python 3.6 support

---

.github/workflows/docs.yaml
docs/_static/README.txt
docs/api.rst
docs/conf.py
msgpack/_packer.pyx
msgpack/_unpacker.pyx
msgpack/ext.py
msgpack/fallback.py
tox.ini

sphinx-related work

---

docs/conf.py
msgpack/__init__.py
msgpack/ext.py
msgpack/fallback.py
pyproject.toml
setup.cfg
setup.py
test/test_buffer.py
test/test_memoryview.py
test/test_obj.py
test/test_pack.py
test/test_seq.py
test/test_subtype.py
test/test_timestamp.py

move project metadata to pyproject.toml

---

.readthedocs.yaml

Should fix this recently seen build failure:
```
Error
The configuration file required to build documentation is missing from your project.
Add a configuration file to your project to make it build successfully.
Read more at https://docs.readthedocs.io/en/stable/config-file/v2.html
```

add a basic .readthedocs.yaml file

---

.readthedocs.yaml

currently, api docs seem rather empty.
try:
- apt install build-essential (so we have gcc, make, etc.)
- install from requirements.txt
- "make cython"
- "pip install ."

fix .readthedocs.yaml, fixes #559

---

msgpack/_packer.pyx
msgpack/buff_converter.h

implement buffer protocol

---

msgpack/_packer.pyx
msgpack/pack.h

- use `except -1` instead of manual error handling
- use `PyUnicode_AsUTF8AndSize()`
- use `_pack()` and `_pack_inner()` instead of `while True:`

cython: better exception handling

---

msgpack/_packer.pyx
test/test_buffer.py

* check buffer exports
* add error messages

better error checks

---

Makefile
msgpack/__init__.py
msgpack/ext.py
msgpack/fallback.py
pyproject.toml
setup.py
test/test_buffer.py
test/test_except.py
test/test_extension.py
test/test_limits.py
test/test_memoryview.py
test/test_newspec.py
test/test_obj.py
test/test_pack.py
test/test_read_size.py
test/test_seq.py
test/test_sequnpack.py
test/test_stricttype.py
test/test_subtype.py
test/test_timestamp.py
test/test_unpack.py

* use isort
* fallback: use BytesIO instead of StringIO. We had dropped Python 2 already.

Cleanup code and pyproject

---

pyproject.toml
setup.py

User can not cythonize during `pip install msgpack`.
So remove cython from build dependency.
If user need to use another Cython, user should download sdist, unzip, manually cythonize, and `pip install .`.

do not install cython as build dependency

---

msgpack/unpack.h

9af421163cb8081414be347038dee7a82b29e8dd in Cython (not released yet) removed back-compatibility `#define`.
This was the most obvious fix, but I'm not sure how far back it works.  I can also put the required `#define` (conditionally) at the top of this file if you would prefer that.

MNT: use PyLong_* instead of PyInt_*

---

pyproject.toml

Wheels have already been published but it'd be nice to declare support in PyPI via the classifier (https://pyreadiness.org/3.13/).

Add Python 3.13 trove classifier

---

.github/workflows/test.yml
.github/workflows/wheel.yml

PR Description:
* The adoption of Windows on ARM (WoA) devices is steadily increasing, yet many Python wheels are still not available for this platform.
* GitHub Actions now offer native CI runners for Windows on ARM devices (windows-11-arm), enabling automated builds and testing.
* Currently, official msgpack-python Python wheels are not provided for Windows ARM64 and thus users/developers were facing difficulties using popular msgpack-python library natively.
* This PR introduces support for building msgpack-python wheels on Windows ARM64, improving accessibility for developers and end users on this emerging platform.

ci: add support for building windows on arm wheels
