msgpack/msgpack-python

- README.rst
> README.rst: Add code-blocks

- .travis.yml
> travis: Use cython 0.22

- msgpack/_unpacker.pyx
- msgpack/unpack_template.h
> Decrease refcnt when error happend while unpacking

- msgpack/pack.h
- msgpack/unpack.h
- msgpack/unpack_template.h
> refactor C code

- msgpack/_packer.pyx
- msgpack/fallback.py
- test/test_extension.py
Here's an implementation in the same spirit as the ones suggested in comments to pull request #134, also addressing issue #133, in the specific case of long integers that overflow.
> Default function on int overflow

- .travis.yml
Cython provides manylinux1 wheel now.
https://pypi.python.org/pypi/Cython
> Use manylinux1 wheel for Cython

- msgpack/fallback.py
It can avoid unnecessary slice.
And use bytearray as buffer since overhead is acceptable now.
> Use struct.unpack_from instead of struct.unpack

- msgpack/unpack.h
- setup.py
> Fix ext_hook call

- msgpack/_packer.pyx
- msgpack/fallback.py
- test/test_pack.py
> Packer accepts bytearray objects

- msgpack/_unpacker.pyx
- msgpack/fallback.py
> Deprecate write_bytes option in Unpacker.

- Makefile
- README.rst
- ci/runtests.bat
- msgpack/_packer.pyx
- msgpack/_unpacker.pyx
- msgpack/fallback.py
- msgpack/unpack.h
- test/test_limits.py
- test/test_pack.py
- test/test_stricttype.py
- test/test_unpack.py
> Add raw_as_bytes option to Unpacker.

- msgpack/_packer.pyx
- msgpack/fallback.py
> Packer.pack() reset buffer on exception

- msgpack/fallback.py
> Fix memory leak in pure Python Unpacker.feed()

- msgpack/__init__.py
- msgpack/_unpacker.pyx
- msgpack/fallback.py
> Move unpack() from each implementation to __init__.

- msgpack/__init__.py
- msgpack/_unpacker.pyx
- msgpack/fallback.py
Reverts msgpack/msgpack-python#286
> Revert "Move unpack() from each implementation to __init__."

- msgpack/fallback.py
> Fix Unpacker.feed() drops unused data in buffer.

- .travis.yml
- Makefile
- docker/runtests.sh
- msgpack/__init__.py
- msgpack/_msgpack.pyx
- setup.py
There were `_packer.so` and `_unpacker.so`.
But single module is simpler than double module.
Merge extension module into single `_msgpack.so`.
> Merge extension module

- msgpack/_packer.pyx
- msgpack/_unpacker.pyx
- msgpack/exceptions.py
- msgpack/fallback.py
> Remove deprecated exception classes

- ChangeLog.rst
- Makefile
- msgpack/_unpacker.pyx
- msgpack/exceptions.py
- msgpack/fallback.py
- msgpack/unpack_template.h
- test/test_except.py
> Add StackError and FormatError

- msgpack/_unpacker.pyx
- msgpack/fallback.py
- msgpack/unpack.h
- test/test_except.py
> unpacker: Add `strict_map_key` option

- msgpack/fallback.py
- msgpack/unpack.h
> Intern map keys

- Makefile
- msgpack/_cmsgpack.pyx
- msgpack/_packer.pyx
- msgpack/_unpacker.pyx
- msgpack/ext.py
- msgpack/fallback.py
- msgpack/unpack.h
- test/test_timestamp.py
> Support datetime.

- benchmark/benchmark.py
Following the changes in d782464.
> Fix benchmark extension module import

- msgpack/unpack.h
- test/test_timestamp.py
> Fix overflow in unpacking timestamp to datetime

- README.md
> Updated readme to make it more clear about Python 2 support

- .github/workflows/mac.yml
> mac: Provide Universal2 wheel

- msgpack/ext.py
> minor type in exception message
